// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATQfpI-6-rrfSJTj51YEB99eB7OugLlM',
    appId: '1:236128306061:android:a69efa0c3c975942e8b3c4',
    messagingSenderId: '236128306061',
    projectId: 'teship-c3909',
    databaseURL: 'https://teship-c3909-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'teship-c3909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx_f19JeHFjURja2hCfqURxaEjpY2lbsw',
    appId: '1:236128306061:ios:4bedbf48c968abb7e8b3c4',
    messagingSenderId: '236128306061',
    projectId: 'teship-c3909',
    databaseURL: 'https://teship-c3909-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'teship-c3909.appspot.com',
    androidClientId: '236128306061-d99eoegko6h2ml3lovnfr5ctopoj9euh.apps.googleusercontent.com',
    iosClientId: '236128306061-pnivd952a0maoccil8b1b3a7crboq8mq.apps.googleusercontent.com',
    iosBundleId: 'com.vibelabs.teship',
  );
}
