/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_eye_off_gray.png)
  final ic_eye_off_gray = r'assets/images/auth/ic_eye_off_gray.png';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_create_order_gray.svg)
  final ic_create_order_gray = r'assets/images/auth/ic_create_order_gray.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_home_green.svg)
  final ic_home_green = r'assets/images/auth/ic_home_green.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/logo_login.png)
  final logo_login = r'assets/images/auth/logo_login.png';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_cancel_x.png)
  final ic_cancel_x = r'assets/images/auth/ic_cancel_x.png';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_eye_gray.png)
  final ic_eye_gray = r'assets/images/auth/ic_eye_gray.png';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_green_uncheck.svg)
  final ic_green_uncheck = r'assets/images/auth/ic_green_uncheck.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_profile_gray.svg)
  final ic_profile_gray = r'assets/images/auth/ic_profile_gray.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_home_gray.svg)
  final ic_home_gray = r'assets/images/auth/ic_home_gray.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_green_check.svg)
  final ic_green_check = r'assets/images/auth/ic_green_check.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_report_gray.svg)
  final ic_report_gray = r'assets/images/auth/ic_report_gray.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/auth/ic_order_gray.svg)
  final ic_order_gray = r'assets/images/auth/ic_order_gray.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_decrease_green.svg)
  final ic_decrease_green = r'assets/images/dashboard/ic_decrease_green.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_decrease_gray.svg)
  final ic_decrease_gray = r'assets/images/dashboard/ic_decrease_gray.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_dropdown_green.svg)
  final ic_dropdown_green = r'assets/images/dashboard/ic_dropdown_green.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/logo_forgot_pass.png)
  final logo_forgot_pass = r'assets/images/dashboard/logo_forgot_pass.png';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_right.svg)
  final ic_right = r'assets/images/dashboard/ic_right.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_logout_green.svg)
  final ic_logout_green = r'assets/images/dashboard/ic_logout_green.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_reload_green.svg)
  final ic_reload_green = r'assets/images/dashboard/ic_reload_green.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/bg_empty_order.png)
  final bg_empty_order = r'assets/images/dashboard/bg_empty_order.png';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_change_password_green.svg)
  final ic_change_password_green = r'assets/images/dashboard/ic_change_password_green.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_add_green.svg)
  final ic_add_green = r'assets/images/dashboard/ic_add_green.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_check_done_blue.svg)
  final ic_check_done_blue = r'assets/images/dashboard/ic_check_done_blue.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_check_white.svg)
  final ic_check_white = r'assets/images/dashboard/ic_check_white.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_store_info_green.svg)
  final ic_store_info_green = r'assets/images/dashboard/ic_store_info_green.svg';

  /// ![](/Users/nganhuynh/TeShip/assets/images/dashboard/ic_store.png)
  final ic_store = r'assets/images/dashboard/ic_store.png';

  /// ![](/Users/nganhuynh/TeShip/assets/images/splash/splash_logo_vibelab.png)
  final splash_logo_vibelab = r'assets/images/splash/splash_logo_vibelab.png';
}

class _SvgResources {
  const _SvgResources();
}
